In [34]:
import numpy as np
import numpy.linalg as la

In [10]:
# creating an array
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
type(a)

numpy.matrix

In [12]:
A = np.matrix([[0,1],[-2,-3]])
B = np.matrix([[1,0],[3,-2]])

In [16]:
# adding 2 matrices.
C = A + B
print("A + b = ",C)

A + b =  [[ 1  1]
 [ 1 -5]]


In [17]:
# subtracting two matrices.
C = A - B
print("A - B = ",C)

A - B =  [[-1  1]
 [-5 -1]]


In [18]:
# multiplying two matrices.
C = A * B
print("A * B = ",C)

A * B =  [[  3  -2]
 [-11   6]]


In [27]:
mat1 = np.array([[1,3,7,2],[5,8,-9,0],[6,-7,11,12]])
print(mat1)
aTranspose = np.transpose(mat1)
print("transpose of A : \n", aTranspose)

[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
transpose of A : 
 [[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


In [33]:
mat2 = np.array([[1,5],[4,5],[3,2],[7,8]])
print(mat2)
bTranspose = np.transpose(mat2)
print("transpose of b : \n", bTranspose)

[[1 5]
 [4 5]
 [3 2]
 [7 8]]
transpose of b : 
 [[1 4 3 7]
 [5 5 2 8]]


In [39]:
matOne = np.array([[1,2],[3,4]])
aDet = la.det(A)
print(aDet)

2.0


In [38]:
matTwo = np.array([[-1,3,0],[2,1,-5],[1,4,-2]])
bDet = la.det(matTwo)
print(bDet)

-21.00000000000001


In [40]:
aInv = la.inv(matOne)
print(aInv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
bInv = la.inv(matTwo)
print(bInv)

[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


In [46]:
aEig , v = la.eig(A)
print(aEig)

[-1. -2.]


In [58]:
aa = np.array([[1,2],[3,4]])
bb = np.array([[5],[6]])
aaI = la.inv(aa)
x = aaI.dot(bb)
x

array([[-4. ],
       [ 4.5]])

In [63]:
haha = np.array([[1,3,2],[2,1,2],[1,3,1]])
hahaInverse = la.inv(haha)
print(hahaInverse)
res = hahaInverse * haha
res


[[-1.   0.6  0.8]
 [ 0.  -0.2  0.4]
 [ 1.  -0.  -1. ]]


array([[-1. ,  1.8,  1.6],
       [ 0. , -0.2,  0.8],
       [ 1. , -0. , -1. ]])