In [18]:
import numpy as np
import numpy.linalg as la

In [19]:
A=np.array([[1,3,7,2],[5,8,-9,0],[6,-7,11,12]])
print("A=");print(A)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [20]:
Atr = np.transpose(A)
print("Transpose of A=");print(Atr)

Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


In [21]:
matB=np.array([[1,2],[3,4]])
matBdet=la.det(matB)
print(matBdet)


-2.0000000000000004


In [22]:
matBinv =la.inv(matB)
print(matBinv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
B=np.array([[-1,3,0],[2,1,-5],[1,4,-2]])
Binv=la.inv(B)
print(Binv)

[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


In [24]:
A=np.array([[0,1],[-2,-3]])
Aeig, v=la.eig(A)
print(Aeig)

[-1. -2.]


In [25]:
b=np.array([[5],[6]])
matBinv = la.inv(matB)
X=matBinv.dot(b)
print(X)

[[-4. ]
 [ 4.5]]
